name: rabbitmq-stream-dotnet-client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-build-test:
    uses: ./.github/workflows/build-test.yaml
  call-publish-myget:
    uses: ./.github/workflows/publish-myget.yaml
